version: '3'
services:
  gpdb5:
        image: "kochanpivotal/gpdb5"
        command: bin/bash
        hostname: "gpdbsne"
        container_name: gpdbsne
        ports:
         - "5432:5432"
         - "5005:5005"
         - "5010:5010"
         - "9022:22"
         - "40000:40000"
         - "40001:40001"
         - "40002:40002"
        expose:
         - "5432"
        volumes:
         - ..:/code
        privileged: true
        tty: true
        networks:
          mynetwork:
            aliases:
              - gpdbsne
              - gpdbsne.localdomain.com
networks:
    mynetwork:
      driver: bridge
